### ISSUE TITLE
/favicon.ico returns 404

### ISSUE THREAD

**Issue by CelDaemon** [karl0dead/karl0dead.github.io#1]
There's no favicon registered, so the browser complains about it, you might want to add a temporary one.

(JK, I just wanted an excuse to say good luck with modern web development)

**Comment by karl0dead** [comment]
Lol,
I'll not change this repository and keep it as it is for memories.
Seems cool to do so
Also hit me up on discord, got some questions on database things ( well of course if you got time ).

Coding is fun..or maybe sometimes

Edit: Also I forgot to say Thanks!

**Comment by CelDaemon** [comment]
Haha, no problem!

I'd also love to answer your questions, but it'd have to be here, I have lost access to my discord again since 2 months ago.
Basically just after saying happy birthday, but I hope everything will get better soon, with me and Kay as well.
but eh, if there's anything you'd want to ask me, you can reach me at devoid@voidgroup.net!
I'll try to respond as soon as I can, but until then, happy coding 👍

**Comment by karl0dead** [comment]
Hello there,
I know it's been 21 days since our last conversation here, and I was supposed to send you an email about my questions on database things, but I think I might have to delay those questions for a while.
Just wanted to apologize for the wait...

But anyways, thanks!

**Comment by CelDaemon** [comment]
Oh no problem, I'm kinda busy here as well!

Although if you do email me, I'll respond as soon as I can.
